# Generated by Django 5.1.5 on 2025-05-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0001_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPairSimilarityStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignments_shared", models.PositiveIntegerField()),
                ("flagged_count", models.PositiveIntegerField(blank=True, default=0)),
                ("average_similarity_score", models.FloatField()),
                ("median_similarity_score", models.FloatField()),
                ("similarity_std_dev", models.FloatField()),
                ("similarity_variance", models.FloatField()),
                ("min_similarity_score", models.FloatField()),
                ("max_similarity_score", models.FloatField()),
                ("average_z_score", models.FloatField()),
                ("median_z_score", models.FloatField()),
                ("min_z_score", models.FloatField()),
                ("max_z_score", models.FloatField()),
                ("total_similarity", models.FloatField()),
                ("total_z_score", models.FloatField()),
                ("cluster_id", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("pair_flagged", models.BooleanField(blank=True, default=False)),
                ("ta_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursecatalog",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
                (
                    "student_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
                (
                    "student_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("course_catalog", "semester", "student_a", "student_b")
                },
            },
        ),
    ]
