# Generated by Django 5.1.5 on 2025-05-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0002_studentpairsimilaritystatistics"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentpairsimilaritystatistics",
            old_name="average_similarity_score",
            new_name="mean_similarity_score",
        ),
        migrations.RenameField(
            model_name="studentpairsimilaritystatistics",
            old_name="average_z_score",
            new_name="mean_z_score",
        ),
    ]
