# Generated by Django 5.1.5 on 2025-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheating",
            "0003_rename_average_similarity_score_studentpairsimilaritystatistics_mean_similarity_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpairsimilaritystatistics",
            name="median_z_score",
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentpairsimilaritystatistics",
            name="pair_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
