# Generated by Django 5.1.5 on 2025-05-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheating",
            "0004_alter_studentpairsimilaritystatistics_median_z_score_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentpairsimilaritystatistics",
            name="flagged_count",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="studentpairsimilaritystatistics",
            name="median_z_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentpairsimilaritystatistics",
            name="ta_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
