# Generated by Django 5.1.5 on 2025-05-02 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cheating",
            "0005_alter_studentpairsimilaritystatistics_flagged_count_and_more",
        ),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationSimilarityStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_unique_pairs", models.PositiveIntegerField(default=0)),
                (
                    "total_flagged_count",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("mean_similarity_score", models.FloatField()),
                ("median_similarity_score", models.FloatField()),
                ("similarity_std_dev", models.FloatField()),
                ("similarity_variance", models.FloatField()),
                ("min_similarity_score", models.FloatField(blank=True, null=True)),
                ("max_similarity_score", models.FloatField(blank=True, null=True)),
                ("mean_z_score", models.FloatField()),
                ("median_z_score", models.FloatField()),
                ("min_z_score", models.FloatField(blank=True, null=True)),
                ("max_z_score", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursecatalog",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
            ],
            options={
                "unique_together": {("course_catalog", "semester")},
            },
        ),
    ]
